{{- if .Values.backup.enabled }}
{{- if eq .Values.backup.engine "native" }}
{{- if or (eq .Values.backup.destination.type "s3") (eq .Values.backup.destination.type "gcs") }}
{{- $dest := .Values.backup.destination -}}
{{- $obj := ternary $dest.s3 $dest.gcs (eq $dest.type "s3") -}}
{{- if not $obj.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-backup
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ $obj.accessKeyId | b64enc | quote }}
  secret-access-key: {{ $obj.secretAccessKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- else if eq .Values.backup.engine "clickhouse-backup" }}
{{- $chb := .Values.backup.clickhouseBackup -}}
{{- if and (eq $chb.remoteStorage "s3") (eq $chb.s3.auth "keys") (not $chb.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-backup
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ $chb.s3.accessKey | b64enc | quote }}
  secret-key: {{ $chb.s3.secretKey | b64enc | quote }}
{{- else if and (eq $chb.remoteStorage "gcs") (eq $chb.gcs.auth "key") (not $chb.gcs.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-backup
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ $chb.gcs.credentialsJson | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
