{{- if and .Values.backup.enabled (eq .Values.backup.destination.type "s3") (not .Values.backup.destination.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-backup
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.backup.destination.s3.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.backup.destination.s3.secretAccessKey | b64enc | quote }}
{{- end }}
